DROP TABLE TAXONOMY CASCADE CONSTRAINTS;
DROP TABLE IUCN_STATUS CASCADE CONSTRAINTS;
DROP TABLE ARTICLES CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE ANIMAL CASCADE CONSTRAINTS;
DROP TABLE MANAGES CASCADE CONSTRAINTS;
DROP TABLE WATCHING CASCADE CONSTRAINTS;
DROP TABLE ABOUT CASCADE CONSTRAINTS;
DROP TABLE VERSION CASCADE CONSTRAINTS;
DROP TABLE ANI_CONTINENT CASCADE CONSTRAINTS;
DROP TABLE ANI_USE CASCADE CONSTRAINTS;
DROP TABLE ANI_FOOD CASCADE CONSTRAINTS;
DROP TABLE ANI_THREATS CASCADE CONSTRAINTS;
DROP TABLE ANI_HABITATS CASCADE CONSTRAINTS;
DROP TABLE ANI_REGION CASCADE CONSTRAINTS;
DROP TABLE ANI_IMG CASCADE CONSTRAINTS;

CREATE TABLE TAXONOMY(
    Kingdom_Name VARCHAR(8)   NOT NULL,
    Phylum_Name  VARCHAR(10)  NOT NULL,
    Class_Name   VARCHAR(20)  NOT NULL,
    Order_Name   VARCHAR(20) Not null,
    Family_Name VARCHAR(20) Not null,
    Genus_Name   VARCHAR(20) Not null,
    Species_Name VARCHAR(20) Not null,
    Scientific_Name    VARCHAR(30) NOT NULL,
    PRIMARY KEY (Scientific_Name)
);

CREATE TABLE IUCN_STATUS(
    IUCN_Status VARCHAR(25)   NOT NULL,
    IUCN_Status_ID	INT	NOT NULL,
    PRIMARY KEY (IUCN_Status_ID)
);

CREATE TABLE ARTICLES(
    URL  NVARCHAR2(1000)   NOT NULL,
    URL_ID	INT	NOT NULL,
    PRIMARY KEY (URL_ID)
);

CREATE TABLE ADMIN(
    Phone_Number char(11) NOT NULL,
    PW varchar(20) NOT NULL,
    ID varchar(20) NOT NULL,
    Name varchar(20) NOT NULL,
    Address varchar(50) NOT NULL,
    Sex char(1),
    PRIMARY KEY (ID)
);

CREATE TABLE ACCOUNT(
    Phone_Number char(11) NOT NULL,
    PW varchar(20) NOT NULL,
    ID varchar(20) NOT NULL,
    Name varchar(20) NOT NULL,
    Address varchar(50) NOT NULL,
    Sex char(1),
    Account_Number varchar(16) NOT NULL,
    Donation char(1) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ANIMAL(
    Length   NUMBER   NOT NULL,
    Weight   NUMBER   NOT NULL,
    Name      VARCHAR(30)   NOT NULL,
    Animal_ID   INT   NOT NULL,
    IUCN_ID   INT   NOT NULL,
    SN_ID   VARCHAR(30)   NOT NULL,
    PRIMARY KEY (Animal_ID),
    FOREIGN KEY (IUCN_ID) REFERENCES IUCN_STATUS(IUCN_Status_ID),
    FOREIGN KEY (SN_ID) REFERENCES TAXONOMY(Scientific_name),
    UNIQUE(Name)
);

CREATE TABLE MANAGES(
    A_ID	INT	NOT NULL,
    AD_ID	varchar(20)	NOT NULL,
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID),
    FOREIGN KEY (AD_ID) REFERENCES ADMIN(ID)
);

CREATE TABLE WATCHING(
    A_ID   INT   NOT NULL,
    AC_ID   varchar(20)   NOT NULL,
    Favorite   char(1)  default 0,
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID),
    FOREIGN KEY (AC_ID) REFERENCES ACCOUNT(ID)
); 


CREATE TABLE VERSION(
    Version    DATE   NOT NULL,
    A_ID    INT NOT NULL,
    CONSTRAINT  VERSION_PK PRIMARY KEY (A_ID),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
);

CREATE TABLE ABOUT(
    URL_ID   INT   NOT NULL,
    A_ID   INT   NOT NULL,
    Record   DATE,   
    FOREIGN KEY (URL_ID) REFERENCES ARTICLES(URL_ID),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
);


CREATE TABLE ANI_CONTINENT(
    A_Continent VARCHAR(20)   NOT NULL,
    A_ID INT NOT NULL,
    CONSTRAINT CONTINENT PRIMARY KEY (A_ID, A_Continent),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
    );
    
CREATE TABLE ANI_USE(
    A_Use VARCHAR(40)   NOT NULL,
    A_ID INT NOT NULL,
   CONSTRAINT USE_PK PRIMARY KEY (A_ID, A_Use),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID) );
    
CREATE TABLE ANI_FOOD(
    A_Food VARCHAR(10)   NOT NULL,
    A_ID INT NOT NULL,
    CONSTRAINT FOOD_PK PRIMARY KEY (A_ID, A_Food),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID) );
    
CREATE TABLE ANI_THREATS(
    A_Threats VARCHAR(70)   NOT NULL,
    A_ID INT NOT NULL,
    CONSTRAINT  THREATS_PK PRIMARY KEY (A_ID, A_Threats),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID) );
    
CREATE TABLE ANI_HABITATS(
    A_Habitats VARCHAR(50)   NOT NULL,
    A_ID INT NOT NULL,
    CONSTRAINT  HABITATS_PK PRIMARY KEY (A_ID, A_Habitats),
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
   );
    
CREATE TABLE ANI_REGION(
     A_Region VARCHAR(70)   NOT NULL,
     A_ID INT NOT NULL,
     CONSTRAINT  REGION_PK PRIMARY KEY (A_ID, A_Region),
     FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
    );     

CREATE TABLE ANI_IMG (
    A_ID   INT   NOT NULL,
    IMG  NVARCHAR2(1000)   NOT NULL,
    FOREIGN KEY (A_ID) REFERENCES ANIMAL(Animal_ID)
);